### PR TITLE
Add phpstorm 9 preferences

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@alexispeter please review
I copied back the settings and adjust the files to how phpstorm9 writes them

**Comment by alexispeter** [comment]
ok great

**Comment by njam** [comment]
@cargomedia/dev PhpStorm 9 config is now in osx-setup! The new version seems to work fine so far.

On a related topic: I've noticed that the change of hostname for the application has invalidated PhpStorm's "server configuration" used for remote debugging.
I'd recommend to check your project settings according to: https://github.com/cargomedia/vagrant-phpstorm-tunnel#phpstorm

**Comment by njam** [comment]
@cargomedia/dev false alarm about the "server configuration" change, I think we should keep the "hostname" as it is, will be done in https://github.com/cargomedia/CM/pull/1845 and https://github.com/cargomedia/sk/pull/1861.

Just make sure to have "www.cm.dev" in your "server configuration"!

**Pull request merged**
