### PR TITLE
Install caniuse-cmd

### PR DESCRIPTION
**Pull request by njam**
@vogdb please review

### CODE REVIEW

**Comment by vogdb** [comment]
I'm not sure but I think we can always install here the latest version. Wdyt? It's just a database without hard dependencies. Can we put smth like `^1.0` ?

**Comment by njam** [comment]
Generally agree, but we can't easily check it in the script. I would leave it for now, wdyt?

**Comment by vogdb** [comment]
okkkey

**Comment by vogdb** [comment]
lgtm!

**Pull request merged**
