### PR TITLE
Update vagrant plugin versions

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
I could install flawlessly in my mac with vagrant 1.8.4

**Comment by njam** [comment]
Just to be sure, did you check these two things?
- Run a "fresh" install - i.e.:
  1. ugprade vagrant
  2. uninstall all plugins (`rm -rf ~/.vagrant.d/gems ~/.vagrant.d/plugins.json`
  3. install plugins with this script
- Check the the most important use cases still work:
  1. puppet-packages: destroy VM and then run some specs
  2. sk or denkmal: destroy VM and the provision it

We need to be careful with vagrant et al, because it's in the every day toolkit for the team.

**Comment by ppp0** [comment]
I'm on point 2

**Comment by kris-lab** [comment]
@ppp0 are the specs running for you? I experience some troubles on `vagrant provision Debian-7 {"DISABLE_PROXY"=>"true"}` step.

**Comment by ppp0** [comment]
No problems so far! @kris-lab snapshots are now a built-in feature of vagrant. I commented the line out where the plugin gets installed. May be this was the cause?

**Comment by ppp0** [comment]
Related to https://github.com/cargomedia/puppet-packages/pull/1361

**Comment by njam** [comment]
- vagrant-plugins.sh: Let's *not* remove `.vagrant.d` - for two reasons:
 - We can't assume that we're managing this directory fully. There's configuration in there and other plugins, we shouldn't delete all of that.
 - osx-setup is supposed to install and upgrade, not to re-install.

> snapshots are now a built-in feature of vagrant

The CLI interface is very different - compare [built-in](https://www.vagrantup.com/docs/cli/snapshot.html) and [plugin](https://github.com/dergachev/vagrant-vbox-snapshot). So if you didn't install the plugin, how did puppet-packages' spec helper create those snapshots?

**Comment by ppp0** [comment]
As discussed, there is no valid upgrade procedure in place for vagrant. This is an installation on personal developer laptops which might contain personal data. Still, for vagrant and its plugins to be updated, the directory `./vagrant.d` needs to be cleaned up.

Let's delete all contents except `./vagrant.d/boxes`

**Comment by ppp0** [comment]
* `.vagrant.d/` : somewhat agree.

>osx-setup is supposed to install and upgrade

This is exactly the problem. Upgrade will be impeded by

**Comment by ppp0** [comment]
paired w/ @kris-lab

**Pull request merged**
