### PR TITLE
Install less compiler

### PR DESCRIPTION
**Pull request by njam**
@fvovan @christopheschwyzer please review

### CODE REVIEW

**Comment by fvovan** [comment]
LGTM

**Comment by christopheschwyzer** [comment]
lgtm

**Comment by christopheschwyzer** [comment]
btw. do you need to define the exact version?

**Comment by njam** [comment]
Theoretically not, but our `nodejs.sh` does it like this - I think because in the past we had trouble with some new versions of npm modules..

**Comment by christopheschwyzer** [comment]
I see

**Pull request merged**
