### PR TITLE
Install "rescuetime"

### PR DESCRIPTION
**Pull request by njam**
@kris-lab please review

### CODE REVIEW

**Comment by kris-lab** [comment]
lgtm

**Comment by njam** [comment]
@cargomedia/dev @cargomedia/bizdev 
I can only agree with Timo that [RescueTime](https://www.rescuetime.com/) is worth trying out. It tracks the activities on your computer and categorizes by "productive" and "unproductive". You can then also set goals for certains days etc.

screen shot 2015-01-19 at 09 01 43

**Comment by christopheschwyzer** [comment]
Surveillance activated!

**Comment by njam** [comment]
Also remember to disable this :)

screen shot 2015-01-19 at 10 21 43

**Comment by vogdb** [comment]
So, should we install it now or just wait until the next osx-setup run?

**Comment by njam** [comment]
You should run "osx-setup" every once in a while (e.g. every week)! It takes 5-10 minutes.

**Comment by mariansollmann** [comment]
@njam I activated this. can you please explain what you want to achieve with this tool? Should this be more for self control or do you want us to post this reports somewhere? What is the goal of using this?

**Comment by njam** [comment]
The idea is that - if you want - you can give it a try. It will help you get information about your workday (what applications you use, what websites you visit). You can also set goals (haven't tried yet).

**Comment by tomaszdurka** [comment]
I can see many of us are afraid it's a step towards more invigilation :panda_face: but I understand it's more for self-control and there is no access by other people (aka managers) to this, right?

**Comment by njam** [comment]
There is a "team edition" where some people on a team can see other members' data.
But if you only install the free version on your computer, it will *not* just start sending data to me! :P

**Comment by NicolasSchmutz** [comment]
Now I need most of my time for the rescuetime dashboard. :smile:

**Pull request merged**
