### PR TITLE
Update vagrant plugins

### PR DESCRIPTION
**Pull request by njam**
Especially landrush 0.18

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 please review

Tested common workflows, all works.

**Comment by ppp0** [comment]
lgtm

**Comment by njam** [comment]
@cargomedia/dev @NicolasSchmutz new vagrant plugins!
Remember to run osx-setup from time to time.

Just copy and past the command in "Run the Installer":
https://github.com/cargomedia/osx-setup/#run-the-installer

**Comment by njam** [comment]
@NicolasSchmutz sorry forgot that you *are* a dev..

**Pull request merged**
