### PR TITLE
Deprecate PHP < 5.6

### PR DESCRIPTION
**Pull request by ppp0**
TODO
- [x] remove old php5.4 configs
- [x] add php5.6 configs?
- [x] update readme

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab It looks like this has been solved in #135 alsready. I update the README and it should be fine. Of course, one needs to follow the procedure in https://github.com/cargomedia/osx-setup/pull/137#issuecomment-251686799

@kris-lab please review

**Comment by kris-lab** [comment]
As discussed let's remove also old `php5.4` config files.

**Comment by ppp0** [comment]
Here the diff between a brew-installed php.ini (red) and our former customized (?) php.ini (green)

```diff
81,83c81,83
< ; php.ini-development is very similar to its production variant, except it is
< ; much more verbose when it comes to errors. We recommend using the
< ; development version only in development environments, as errors shown to
---
> ; php.ini-development is very similar to its production variant, except it's
> ; much more verbose when it comes to errors. We recommending using the
> ; development version only in development environments as errors shown to
140a141,150
> ; session.bug_compat_42
> ;   Default Value: On
> ;   Development Value: On
> ;   Production Value: Off
> 
> ; session.bug_compat_warn
> ;   Default Value: On
> ;   Development Value: On
> ;   Production Value: Off
> 
296c306,307
< ; or per-virtualhost web server configuration file.
---
> ; or per-virtualhost web server configuration file. This directive is
> ; *NOT* affected by whether Safe Mode is turned On or Off.
301c312,313
< ; It receives a comma-delimited list of function names.
---
> ; It receives a comma-delimited list of function names. This directive is
> ; *NOT* affected by whether Safe Mode is turned On or Off.
306c318,319
< ; It receives a comma-delimited list of class names.
---
> ; It receives a comma-delimited list of class names. This directive is
> ; *NOT* affected by whether Safe Mode is turned On or Off.
393c406
< memory_limit = 128M
---
> memory_limit = 1280M
423c436
< ;                     relying on the fact it is automatically initialized to an
---
> ;                     relying on the fact it's automatically initialized to an
456,457c469,470
< ; For production environments, we recommend logging errors rather than
< ; sending them to STDOUT.
---
> ; It's recommended that errors be logged on production servers rather than
> ; having the errors sent to STDOUT.
471,472c484,485
< ; debugging configuration problems. We strongly recommend you
< ; set this to 'off' for production servers.
---
> ; debugging configuration problems. But, it's strongly recommended that you
> ; leave this setting off on production servers.
573c586
< ; Log errors to syslog (Event Log on Windows).
---
> ; Log errors to syslog (Event Log on NT, not valid in Windows 95).
611,617c624,630
< ; This directive determines which super global data (G,P & C) should be
< ; registered into the super global array REQUEST. If so, it also determines
< ; the order in which that data is registered. The values for this directive
< ; are specified in the same manner as the variables_order directive,
< ; EXCEPT one. Leaving this value empty will cause PHP to use the value set
< ; in the variables_order directive. It does not mean it will leave the super
< ; globals array REQUEST empty.
---
> ; This directive determines which super global data (G,P,C,E & S) should
> ; be registered into the super global array REQUEST. If so, it also determines
> ; the order in which that data is registered. The values for this directive are
> ; specified in the same manner as the variables_order directive, EXCEPT one.
> ; Leaving this value empty will cause PHP to use the value set in the
> ; variables_order directive. It does not mean it will leave the super globals
> ; array REQUEST empty.
670,671c683,685
< ; By default, PHP will output a media type using the Content-Type header. To
< ; disable this, simply set it to be empty.
---
> ; By default, PHP will output a character encoding using
> ; the Content-type: header.  To disable sending of the charset, simply
> ; set it to be empty.
673c687
< ; PHP's built-in default media type is set to text/html.
---
> ; PHP's built-in default is text/html
677c691
< ; PHP's default character set is set to UTF-8.
---
> ; PHP's default character set is set to empty.
679,695c693
< default_charset = "UTF-8"
< 
< ; PHP internal character encoding is set to empty.
< ; If empty, default_charset is used.
< ; http://php.net/internal-encoding
< ;internal_encoding =
< 
< ; PHP input character encoding is set to empty.
< ; If empty, default_charset is used.
< ; http://php.net/input-encoding
< ;input_encoding =
< 
< ; PHP output character encoding is set to empty.
< ; If empty, default_charset is used.
< ; See also output_buffer.
< ; http://php.net/output-encoding
< ;output_encoding =
---
> ;default_charset = "UTF-8"
698,700c696,697
< ; to disable this feature and it will be removed in a future version.
< ; If post reading is disabled through enable_post_data_reading,
< ; $HTTP_RAW_POST_DATA is *NOT* populated.
---
> ; to disable this feature. If post reading is disabled through
> ; enable_post_data_reading, $HTTP_RAW_POST_DATA is *NOT* populated.
702c699
< ;always_populate_raw_post_data = -1
---
> ;always_populate_raw_post_data = On
736,739d732
< ; Directory where the temporary files should be placed.
< ; Defaults to the system default (see sys_get_temp_dir)
< ; sys_temp_dir = "/tmp"
< 
786,787c779,780
< ; use when sending HTTP response code. If set to 0, PHP sends Status: header that
< ; is supported by Apache. When this option is set to 1, PHP will send
---
> ; use when sending HTTP response code. If it's set 0 PHP sends Status: header that
> ; is supported by Apache. When this option is set to 1 PHP will send
890c883,884
< ;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
---
> ;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
> ;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
898a893
> ;extension=php_pspell.dll
901,902c896,897
< ; The MIBS data available in the PHP distribution must be installed. 
< ; See http://www.php.net/manual/en/snmp.installation.php 
---
> ; The MIBS data available in the PHP distribution must be installed.
> ; See http://www.php.net/manual/en/snmp.installation.php
924c919
< ;date.timezone =
---
> date.timezone = "UTC"
946,961c941,943
< ; Use of this INI entry is deprecated, use global input_encoding instead.
< ; If empty, default_charset or input_encoding or iconv.input_encoding is used.
< ; The precedence is: default_charset < intput_encoding < iconv.input_encoding
< ;iconv.input_encoding =
< 
< ; Use of this INI entry is deprecated, use global internal_encoding instead.
< ; If empty, default_charset or internal_encoding or iconv.internal_encoding is used.
< ; The precedence is: default_charset < internal_encoding < iconv.internal_encoding
< ;iconv.internal_encoding =
< 
< ; Use of this INI entry is deprecated, use global output_encoding instead.
< ; If empty, default_charset or output_encoding or iconv.output_encoding is used.
< ; The precedence is: default_charset < output_encoding < iconv.output_encoding
< ; To use an output encoding conversion, iconv's output handler must be set
< ; otherwise output encoding conversion cannot be performed.
< ;iconv.output_encoding =
---
> ;iconv.input_encoding = ISO-8859-1
> ;iconv.internal_encoding = ISO-8859-1
> ;iconv.output_encoding = ISO-8859-1
969c951,954
< ;intl.use_exceptions = 0
---
> 
> [sqlite]
> ; http://php.net/sqlite.assoc-case
> ;sqlite.assoc_case = 0
1029c1014
< ; the 5th parameter to mail().
---
> ; the 5th parameter to mail(), even in safe mode.
1038c1023
< ; Log mail to syslog (Event Log on Windows).
---
> ; Log mail to syslog (Event Log on NT, not valid in Windows 95).
1394,1396c1379,1381
< ; store the session data in those directories.  This is useful if
< ; your OS has problems with many files in one directory, and is
< ; a more efficient layout for servers that handle many sessions.
---
> ; store the session data in those directories.  This is useful if you
> ; or your OS have problems with lots of files in one directory, and is
> ; a more efficient layout for servers that handle lots of sessions.
1413,1420d1397
< ; Whether to use strict session mode.
< ; Strict session mode does not accept uninitialized session ID and regenerate
< ; session ID if browser sends uninitialized session ID. Strict mode protects
< ; applications from session fixation via session adoption vulnerability. It is
< ; disabled by default for maximum compatibility, but enabling it is encouraged.
< ; https://wiki.php.net/rfc/strict_sessions
< session.use_strict_mode = 0
< 
1431c1408
< ; not the be-all and end-all of session hijacking defense, but it's a good start.
---
> ; not the end all be all of session hijacking defense, but it's a good start.
1501a1479,1503
> ; PHP 4.2 and less have an undocumented feature/bug that allows you to
> ; to initialize a session variable in the global scope.
> ; PHP 4.3 and later will warn you, if this feature is used.
> ; You can disable the feature and the warning separately. At this time,
> ; the warning is only displayed, if bug_compat_42 is enabled. This feature
> ; introduces some serious security problems if not handled correctly. It's
> ; recommended that you do not use this feature on production servers. But you
> ; should enable this on development servers and enable the warning as well. If you
> ; do not enable the feature on development servers, you won't be warned when it's
> ; used and debugging errors caused by this can be difficult to track down.
> ; Default Value: On
> ; Development Value: On
> ; Production Value: Off
> ; http://php.net/session.bug-compat-42
> session.bug_compat_42 = On
> 
> ; This setting controls whether or not you are warned by PHP when initializing a
> ; session value into the global space. session.bug_compat_42 must be enabled before
> ; these warnings can be issued by PHP. See the directive above for more information.
> ; Default Value: On
> ; Development Value: On
> ; Production Value: Off
> ; http://php.net/session.bug-compat-warn
> session.bug_compat_warn = On
> 
1531c1533
< ; Use of trans sid may risk your users' security.
---
> ; Use of trans sid may risk your users security.
1637c1639
< mssql.compatibility_mode = Off
---
> mssql.compatability_mode = Off
1721d1722
< ; This affects mb_send_mail() and mbstrig.detect_order.
1725d1725
< ; Use of this INI entry is deprecated, use global internal_encoding instead.
1727,1730c1727,1730
< ; Some encoding cannot work as internal encoding. (e.g. SJIS, BIG5, ISO-2022-*)
< ; If empty, default_charset or internal_encoding or iconv.internal_encoding is used.
< ; The precedence is: default_charset < internal_encoding < iconv.internal_encoding
< ;mbstring.internal_encoding =
---
> ; Some encoding cannot work as internal encoding.
> ; (e.g. SJIS, BIG5, ISO-2022-*)
> ; http://php.net/mbstring.internal-encoding
> ;mbstring.internal_encoding = EUC-JP
1732d1731
< ; Use of this INI entry is deprecated, use global input_encoding instead.
1734,1736d1732
< ; mbstring.encoding_traslation = On is needed to use this setting.
< ; If empty, default_charset or input_encoding or mbstring.input is used.
< ; The precedence is: default_charset < intput_encoding < mbsting.http_input
1738c1734
< ;mbstring.http_input =
---
> ;mbstring.http_input = auto
1740,1746c1736,1737
< ; Use of this INI entry is deprecated, use global output_encoding instead.
< ; http output encoding.
< ; mb_output_handler must be registered as output buffer to function.
< ; If empty, default_charset or output_encoding or mbstring.http_output is used.
< ; The precedence is: default_charset < output_encoding < mbstring.http_output
< ; To use an output encoding conversion, mbstring's output handler must be set
< ; otherwise output encoding conversion cannot be performed.
---
> ; http output encoding. mb_output_handler must be
> ; registered as output buffer to function
1748c1739
< ;mbstring.http_output =
---
> ;mbstring.http_output = SJIS
1759c1750
< ; "auto" detect order is changed according to mbstring.language
---
> ; auto means
1766c1757
< ;mbstring.substitute_character = none
---
> ;mbstring.substitute_character = none;
1780,1781c1771
< ; Default: Off
< ;mbstring.strict_detection = On
---
> ;mbstring.strict_detection = Off
1869,1964d1858
< [opcache]
< ; Determines if Zend OPCache is enabled
< ;opcache.enable=0
< 
< ; Determines if Zend OPCache is enabled for the CLI version of PHP
< ;opcache.enable_cli=0
< 
< ; The OPcache shared memory storage size.
< ;opcache.memory_consumption=64
< 
< ; The amount of memory for interned strings in Mbytes.
< ;opcache.interned_strings_buffer=4
< 
< ; The maximum number of keys (scripts) in the OPcache hash table.
< ; Only numbers between 200 and 100000 are allowed.
< ;opcache.max_accelerated_files=2000
< 
< ; The maximum percentage of "wasted" memory until a restart is scheduled.
< ;opcache.max_wasted_percentage=5
< 
< ; When this directive is enabled, the OPcache appends the current working
< ; directory to the script key, thus eliminating possible collisions between
< ; files with the same name (basename). Disabling the directive improves
< ; performance, but may break existing applications.
< ;opcache.use_cwd=1
< 
< ; When disabled, you must reset the OPcache manually or restart the
< ; webserver for changes to the filesystem to take effect.
< ;opcache.validate_timestamps=1
< 
< ; How often (in seconds) to check file timestamps for changes to the shared
< ; memory storage allocation. ("1" means validate once per second, but only
< ; once per request. "0" means always validate)
< ;opcache.revalidate_freq=2
< 
< ; Enables or disables file search in include_path optimization
< ;opcache.revalidate_path=0
< 
< ; If disabled, all PHPDoc comments are dropped from the code to reduce the
< ; size of the optimized code.
< ;opcache.save_comments=1
< 
< ; If disabled, PHPDoc comments are not loaded from SHM, so "Doc Comments"
< ; may be always stored (save_comments=1), but not loaded by applications
< ; that don't need them anyway.
< ;opcache.load_comments=1
< 
< ; If enabled, a fast shutdown sequence is used for the accelerated code
< ;opcache.fast_shutdown=0
< 
< ; Allow file existence override (file_exists, etc.) performance feature.
< ;opcache.enable_file_override=0
< 
< ; A bitmask, where each bit enables or disables the appropriate OPcache
< ; passes
< ;opcache.optimization_level=0xffffffff
< 
< ;opcache.inherited_hack=1
< ;opcache.dups_fix=0
< 
< ; The location of the OPcache blacklist file (wildcards allowed).
< ; Each OPcache blacklist file is a text file that holds the names of files
< ; that should not be accelerated. The file format is to add each filename
< ; to a new line. The filename may be a full path or just a file prefix
< ; (i.e., /var/www/x  blacklists all the files and directories in /var/www
< ; that start with 'x'). Line starting with a ; are ignored (comments).
< ;opcache.blacklist_filename=
< 
< ; Allows exclusion of large files from being cached. By default all files
< ; are cached.
< ;opcache.max_file_size=0
< 
< ; Check the cache checksum each N requests.
< ; The default value of "0" means that the checks are disabled.
< ;opcache.consistency_checks=0
< 
< ; How long to wait (in seconds) for a scheduled restart to begin if the cache
< ; is not being accessed.
< ;opcache.force_restart_timeout=180
< 
< ; OPcache error_log file name. Empty string assumes "stderr".
< ;opcache.error_log=
< 
< ; All OPcache errors go to the Web server log.
< ; By default, only fatal errors (level 0) or errors (level 1) are logged.
< ; You can also enable warnings (level 2), info messages (level 3) or
< ; debug messages (level 4).
< ;opcache.log_verbosity_level=1
< 
< ; Preferred Shared Memory back-end. Leave empty and let the system decide.
< ;opcache.preferred_memory_model=
< 
< ; Protect the shared memory from unexpected writing during script execution.
< ; Useful for internal debugging only.
< ;opcache.protect_memory=0
< 
1970,1987d1863
< [openssl]
< ; The location of a Certificate Authority (CA) file on the local filesystem
< ; to use when verifying the identity of SSL/TLS peers. Most users should
< ; not specify a value for this directive as PHP will attempt to use the
< ; OS-managed cert stores in its absence. If specified, this value may still
< ; be overridden on a per-stream basis via the "cafile" SSL stream context
< ; option.
< ;openssl.cafile=
< 
< ; If openssl.cafile is not specified or if the CA file is not found, the
< ; directory pointed to by openssl.capath is searched for a suitable
< ; certificate. This value must be a correctly hashed certificate directory.
< ; Most users should not specify a value for this directive as PHP will
< ; attempt to use the OS-managed cert stores in its absence. If specified,
< ; this value may still be overridden on a per-stream basis via the "capath"
< ; SSL stream context option.
< ;openssl.capath=
< 
```

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
lgtm, however I didn't verify this manually. Based on developers feedback in hipchat/development room I assume all this works fine.

**Pull request merged**
