### PR TITLE
Accepting of xcode terms doesn't work anymore

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam @ppp0 could you have a look? for me works good.

**Comment by njam** [comment]
looks good

what about?
> This new `xcode.sh` script could also trigger the installation of the XCode command line tools. So then we could remove that step from the [readme](https://github.com/cargomedia/osx-setup#install-xcode-cli-tools).

**Comment by kris-lab** [comment]
Ahh sorry, didn't see your comment. Will do it!

**Comment by kris-lab** [comment]
@njam please have a look. I am not 100% sure about robustness of this solution. Maybe we should rather have double `IF`. One for checking if `xcode` is not installed (for installing) and second for license (if installed)

**Comment by njam** [comment]
Yes let's do 2 IFs. I think `xcode-select --install` will ask to install either "XCode" or "Xcode CLI Tools". I'm not sure if the latter will create `/Applications/Xcode.app`. Also are you sure the condition is good now? -> Is XCode path *not* available if the license is not accepted?

How about:
- Check if XCode is installed (`xcode-select -p`?)
 - Install XCode if not (`xcode-select --install`)
- Accept XCode license (always?)

To be sure, maybe uninstall XCode?

**Comment by kris-lab** [comment]
- `xcode-select -p` returns the path I am using for check but could be done with exist status 0/1. I am not sure is `xcode-select` available if xcode not installed. Will check then by uninstall.
- always accepts the license makes sense as well

**Comment by kris-lab** [comment]
@njam what about this? works pretty reliably.

**Comment by njam** [comment]
- XCODE_PRINT_PATH: Is only used to check if XCode is installed. So I would suggest to introduce a variable which contains only that information
- Let's stick to wrapping Shell  variables in `{` and `}`.
- You mentioned we run all scripts with `-e` - won't this fail when executing `xcode-select -p` on a machine with no XCode installed?

Maybe something like?:
```sh
#!/bin/bash
set -e

if (xcode-select -p &>/dev/null); then
 XCODE_INSTALLED=true;
else
 XCODE_INSTALLED=false;
fi

if [[ true == "${XCODE_INSTALLED}" ]]; then
 echo "installed";
fi
```

**Comment by kris-lab** [comment]
- `XCODE_PRINT_PATH` should be executed twice. 1st time to check if installed, 2nd time to verify that installed properly?
- ok
- according to google resource, this `xcode-select` is always available in `maverick`, `yosemite` (can you confirm)

**Comment by njam** [comment]
Ah true about executing twice, let's move it to a function then!

Regarding `-e` I meant something different. The command will be available, but it will fail with exit code != 0 when XCode is not installed. This means the bash  script will fail too, and the whole osx-setup will abort?

**Comment by kris-lab** [comment]
- [x] executed twice
- [x] variables wrapped
- [x] `-e` safe mode

@njam please have a look

**Comment by njam** [comment]
lgtm!

Btw you could use `true` and `false` instead of `0` and `1` for some additional syntactic sugar :)

**Comment by kris-lab** [comment]
Agree would be good but no idea how to solve this:
```
xcode.sh: line 3: return: false: numeric argument required 
```
It happens if you wana return `false` or `'false'` or any `string`.

**Comment by njam** [comment]
Ah because `false` is a command so we'd need to run it and return it's result. Probably better with 0/1!
lgtm then!

**Pull request merged**
